### ISSUE TITLE
后端配置项没有正常加载，上传插件不能正常使用！

### ISSUE THREAD

**Issue by cacacai** [BigKuCha/yii2-ueditor-widget#25]
不知道为什么一直报这个错

**Comment by Darkgel** [comment]
@cacacai ，使用上传插件的时候，需要加载相应的配置，这部分配置是通过一个ajax请求获取的（发起的请求是test/upload?action=config&&noCache=这里是时间戳），相应的代码是ueditor.all.js中的doAjax(url, ajaxOptions)函数。如果你在配置还没加载完成的时候点击上传按钮的话，就会出现“后端配置项没有正常加载，上传插件不能正常使用！”，等配置加载完成后再点击就不会了

**Comment by 18979909059** [comment]
建议检查一下是否有权限，在浏览器中可以看见获取配置提示403错误

**Comment by jiashengcai** [comment]
好的，非常感谢大家
